version: '2'
services:
  tigergraph:
    container_name: tigergraph
    image: tigergraph
    build: 
      context: ./LDAP/
      dockerfile: Dockerfile
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Tigergraph"
      LDAP_DOMAIN: "tigergraph.com"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
      - ./ldif/populate.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    command: --copy-service
    ports:
      - "389:389"
      - "636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: "tigergraph.com"
    hostname: "ldap-server"
    depends_on:
      - tigergraph